Parameters:
  NetworkStackName:
    Description: Provide the name of the NetworkStack to encase this instance.
    Type: String
  MyFlavor:
    Description: Provide the s3 resource path for the flavor you would like to run.
    Default: s3://bc-minecraft-repo/servers/vanilla
    Type: String
  MyWorld:
    Description: provide the s3 resource path for the world you would like to run.
    Default: s3://bc-minecraft-repo/worlds/world1
    Type: String
  MyKeyPair:
    Description: Amazon EC2 Key Pair
    Type: AWS::EC2::KeyPair::KeyName
  MyInstanceType:
    Description: Instance Type for Server
    AllowedValues:
    - t3.micro
    - m5.large
    - r5.large
    - m5.xlarge
    - r5.xlarge
    Default: m5.large
    Type: String
Resources:
  Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "mc-ec2-cf-deletePolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "cloudformation:DeleteStack"
            Resource: !Ref "AWS::StackId"
      Roles:
        -
          Fn::ImportValue: !Sub "${NetworkStackName}-myIamRoleArn"
  SpotFleet:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        IamFleetRole:
          Fn::ImportValue: !Sub "${NetworkStackName}-MyFleetRoleArn"
        TargetCapacity: 1
        LaunchSpecifications:
        - IamInstanceProfile:
            Arn:
              Fn::ImportValue: !Sub "${NetworkStackName}-MyInstanceProfileArn"
          ImageId: 'ami-082b5a644766e0e6f'
          UserData:
            Fn::Base64:
              Fn::Join:
                - ""
                -
                  - "#!/bin/bash\n"
                  - "cd /home/ec2-user\n"
                  - "aws s3 cp s3://bc-minecraft-repo/scripts/configure-ec2 configure-ec2\n"
                  - "chmod +x configure-ec2\n"
                  - "./configure-ec2 "
                  - !Ref MyWorld
                  - " "
                  - !Ref MyFlavor
                  - " "
                  - !Ref AWS::StackName
                  - "\n"
          InstanceType: !Ref MyInstanceType
          KeyName: !Ref MyKeyPair
          SecurityGroups:
          - GroupId:
              Fn::ImportValue: !Sub "${NetworkStackName}-MyEC2SecGroupGroupId"
          SubnetId:
            Fn::ImportValue: !Sub "${NetworkStackName}-MySubnetAId"
