#!/bin/bash
if [[ $# -ne 3 ]]; then
	echo "Usage: $0 <s3 world url> <s3 flavor url> <Cloudformation StackName" > error.log
	exit
fi

WORLD_URL=$1
FLAVOR_URL=$2
STACK_NAME=$3
ENV_FILE=/etc/mineshell.env

sudo yum install -y java-1.8.0 gcc-c++
# This script adds the nodejs repository to yum
curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -
sudo yum install -y nodejs

echo "WORLD_URL=$WORLD_URL" > $ENV_FILE
echo "FLAVOR_URL=$FLAVOR_URL" >> $ENV_FILE
echo "STACK_NAME=$STACK_NAME" >> $ENV_FILE

aws s3 sync s3://bc-minecraft-repo/scripts autostack-scripts

chown -R ec2-user:ec2-user *

cp autostack-scripts/mineService.service /etc/systemd/system/mineService.service
systemctl start mineService
